<?php
// Load a BBC news page and format it for a typical Ceefax news page.
// Uses simple_html_dom.php which can be downloaded from sourceforge
include "simple_html_dom.php";
// We can set up some template values here instead of hard coding them
// Something line
// Copy a header. Find the starting line, style and number of lines.
// Also get ready to load in the footer
$line=4;	// The first line that we can write on.
/**
 * \param $file : Filename of the source page
 * \param $content : The Section attribute from the news page
 * \param $mppss : Magazine, Page number, subcode 10000 to 7FF99
 */
function outputheader($file,$content,$mppss)
{
	// Calculate the next page
	// $next=$mppss[0].(substr($mppss,1,2)+1)%100;
	$next=sprintf("%1d%02d",$mppss[0],(substr($mppss,1,2)+1)%100);	// This is a bit crude. Next page
	//echo "RE,$next\r\n";
	echo "DS,Inserter\r\n";
	echo "SP,$file\r\n";
	echo "DE,Autogenerated from BBC News: $content\r\n";
	echo "PN,$mppss\r\n";	// Page number
	// echo "RE,$content\n";
	echo "CT,15,C\r\n";	// cycle/time TODO
	echo "SC,1\r\n";	// Not sure! Think we need this for subpages
	echo "PS,8040\r\n";	// Page settings TODO
	echo "MS,0\r\n";	// Not sure
	
	echo "OL,0,XXXXXXXXCEEFAX 1 mpp DAY dd MTH hh:nn/ss\r\n"; // An inserter will not use row 0, but wxTED and Muttlee do.
	// Which header do we want?
	
	// BBC News header - "Politics"
	// prolly should remove the slash and all following text
	
	// Here we map from the RSS URL to the old category names. This table is obviously not complete!
	$category="UK"; // If the category is not implemented, we will put out home.
	if (strpos($content,"politics")) $category="Politics";
	if (strpos($content,"world")) $category="World";
	if (strpos($content,"uk")) $category="UK";
	if (strpos($content,"health")) $category="Health";
	if (strpos($content,"technology")) $category="Technology";
	switch ($category)
	{
	case "Health" : ;
		echo 'OL,1,—j#3kj#3kj#3k”“ | |h<$|,|h4h||4| | '."\r\n";
		echo 'OL,2,—j $kj $kj'." 'k”“ #jw1#ju0j5 #  "."\r\n";
		//echo 'OL,2,—j $kj $kj'." 'k”“ #jw1#ju0j5 # '"."\r\n";
		echo 'OL,3,—"###"###"###”///,/,-,.,/,-,.-./,/,/////'."\r\n";
		break;
	case "Technology" : ;
	case "Science and Environment" : ;
	case "Science &amp; Environment" : ;
		echo 'OL,1,Wj#3kj#3kj#3kT]S |,h<$|h<$|0|h<$|,      '."\r\n";
		echo 'OL,2,Wj $kj $kj \'kT]S sju0jw1)ju0s      '."\r\n";
		echo 'OL,3,W"###"###"###T///,,-,.,-,.,/,-,.,,//////'."\r\n";
		break;
	case "Magazine" : ;
	case "Entertainment and Arts" : ;
	case "Entertainment &amp; Arts" : ;
	case "In Pictures" : ;
	case "Education" : ;
		echo 'OL,1,—j#3kj#3kj#3k”“    h4h4|,|h<<|h<$'."\r\n";	// Home
		echo 'OL,2,—j $kj $kj \'k”“    j7k5pj55jw1'."\r\n";
		echo 'OL,3,—"###"###"###”//////-.-.,,,-..,-,.//////'."\r\n";
		echo 'OL,22,„ƒHome news digest‡141ƒWorld digest‡142'."\r\n";  
		echo 'OL,23,„ƒNews Index‡102ƒFlash‡150ƒRegional‡160'."\r\n";  		
		break;
	// Use HOME for want of a better option
	case "Business" : ;	// For mag 1 news, not mag 2 business
	case "Formula 1";	// Perhaps move this to Sport
	case "Football";	// Perhaps move this to Sport
	case "Cricket";	// Perhaps move this to Sport
	case "Rugby League";	// Perhaps move this to Sport
	case "Rugby Union";	// Perhaps move this to Sport	
	case "Boxing";	// Perhaps move this to Sport
	case "Tennis";	// Perhaps move this to Sport
	case "UK" : ;
	case "England" : ;
	case "London" : ;
	case "Manchester" : ;
	case "Scotland" : ;
	case "Scotland/Glasgow and West" : ;
	case "Northern Ireland" : ;
	case "England/Beds Bucks and Herts" : ;
	case "Scotland/Scotland politics" : ;
	case "Stoke and Staffordshire" : ;
	case "Tyne and Wear" : ;
	case "South Yorkshire" : ;
	case "Lancashire" : ;
	case "Suffolk" : ;
	case "Sussex" : ;
	case "England/Birmingham and Black Country" : ;	
	case "South East Wales" : ;
	case "Education &amp; Family" : ;
		echo 'OL,1,—j#3kj#3kj#3k”“    h4h4|,|h<<|h<$'."\r\n";	// Home
		echo 'OL,2,—j $kj $kj \'k”“    j7k5pj55jw1'."\r\n";
		echo 'OL,3,—"###"###"###”//////-.-.,,,-..,-,.//////'."\r\n";
		echo 'OL,22,„ƒHome news digest‡141ƒWorld digest‡142'."\r\n";  
		echo 'OL,23,„ƒNews Index‡102ƒFlash‡150ƒRegional‡160'."\r\n";  		
		break;
	case "Europe" : ;
	case "House of Commons" : ;
	case "Asia" : ;
	case "Africa" : ;
	case "Middle East" : ;
	case "World/Asia/China" : ;
	case "Latin America" : ;
	case "US and Canada" : ;
	case "US &amp; Canada" : ;
	case "World" : ;
	case "China" : ;
	case "Latin America &amp; Caribbean" : ;
		echo 'OL,1,—j#3kj#3kj#3k”“   |hh4|,|h<l4| h<l0'."\r\n";    // World
		echo 'OL,2,—j $kj $kj \'k”“   ozz%pj7k4pjuz%'."\r\n";        
		echo 'OL,3,—"###"###"###”/////-,,/,,,-.-.,,-,,/////'."\r\n";  
		echo 'OL,22,„ƒHome news digest‡141ƒWorld digest‡142'."\r\n";  
		echo 'OL,23,„ƒNews Index‡102ƒFlash‡150ƒRegional‡160'."\r\n";  		
		break;
	
	case "Politics" :
		echo 'OL,1,—j#3kj#3kj#3k”“ h<|h<|h4 |(|$|h<$|,$   '."\r\n";	// Politics
		echo 'OL,2,—j $kj $kj \'k”“ j7#juju0  ju0s{5   '."\r\n";
		echo 'OL,3,—"###"###"###”///-./-,,-,.,/,/,-,.,,.///	'."\r\n";
		// Line 22 should have a politics link or a link to another aspect of the same story
		echo 'OL,22,„ƒHome news digest‡141ƒWorld digest‡142'."\r\n";  
		echo 'OL,23,„ƒNews Index‡102ƒFlash‡150ƒRegional‡160'."\r\n";
		break;
	}
	echo 'OL,24,Next News‚News IndxƒHeadlines†Main Menu'."\r\n";	
	printf( "FL,%d,102,101,100,F,109\r\n",$next);
}

function outputline($lineNumber,$colour,$text,$maxline)
{
	$utext=	htmlspecialchars_decode ($text,ENT_QUOTES);		// Decode html entities
	$utext=explode('\r\n',wordwrap($utext,39,'\r\n'));		// Wrap the text into separate lines
	//echo "CO,".count($utext)."\r\n";
	if (count($utext)+$lineNumber>$maxline)					// This would overflow so forget it
	{	
		return 0;
	}
	$count=0;
	foreach ($utext as $line)							// Output all the lines
	{
		$ln=$lineNumber+$count;
		echo "OL,".$ln.",$colour$line\r\n";
		$count++;
	}
	return $count; 	// return the number lines used
}

$page="page0.html";		// The default input name
$mpp="10000";
/* From the command line?
 * newsformat.php <source news page> <target text page>
 * Example: php newsformat.php page0.html 10000
 */
if (isset($argc))
{
	$page=$argv[1];
	if ($argc>2)
		$mpp=$argv[2];
	//echo "Page=$page, argc=$argc\n";
}

$html = file_get_html($page);	// Get the whole file
$found=false;

// <meta property="og:url" content="http://www.bbc.co.uk/news/uk-politics-eu-referendum-35584189" />
if (is_object($html))
{
	$cat= $html->find('meta[property="og:url"]');	// Category of story
	//echo $cat[0]->content;
	//exit;
	//$content=str_get_html($cat[0]);
	// echo "RE,".$cat[0]->content."\n";
	outputheader($page,$cat[0]->content,$mpp); 
	$body= $html->find('div[class=story-body]');	// Extract the body part as HTML
	$body=str_get_html($body[0]);	// Convert it back to DOM
// 	$element=$body->find('h1[class=story-header]'); // Old format
//	$element=$body->find('h1[class="story-body__h1"]');
	$element=$html->find('meta[property="og:title"]');
	//echo($element);
	if (is_array($element))
	{
		$line+=outputline($line,'ƒ',$element[0]->content,21);	// Yellow
	}
	else
		$line+=outputline($line,'ƒ',"can not find story title",21);	// Yellow
	$intro=$body->find('p[class=story-body__introduction]');	// Intro para is white
//echo "RE,".count($intro)."\r\n";
// If there is no introduction we won't be able to render this page
if (!count($intro))
	$line+=outputline($line,' ',"Missing introduction error",21);
else
	$line+=outputline($line,' ',$intro[0]->plaintext,21);
$line++;	// And an extra line space
$paracount=0;
foreach ($body->find('p') as $element)
{
	if ($paracount>4)
		break;
	if ($line>21)
		break;
	if ($found) 
	{
		$line+=outputline($line++,'†',$element->plaintext,21);
		$paracount++;
	}
	// We output nothing until we get to class=introduction
	// This is the white opening paragraph.
	// Then we do more p tags until we run out of space
	if (strpos($element,"introduction"))
		$found=true;	
}
}
else
outputheader($page,"This page needs some work",$mpp); 

if (!$found)
	echo "OL,1,Sorry.this story can not be displayed";
// echo "FL,0,0,0,0,0,0\r\n";
?>